name: 'Github Actions Mirror to Gitlab'

on: [push, delete]

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:Aericpp/Rules.git
          ssh_private_key:
            ${{ secrets.GITLAB_SYNC }}
