name: 'Github Actions Release'

on: [push, delete]

jobs:
  action_release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: compile v-mod
        run: |
          chmod +x entrypoint.sh
          bash entrypoint.sh

      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: config
          path: |
            release/

      - name: release version
        id: release_version
        run: |
          echo "RELEASE_VERSION=$(date +"%Y%m%d_%H-%M-%S")" >> $GITHUB_OUTPUT

      - name: notify
        run: |
          curl "${{secrets.PUSH_URL}}?title=规则发布"

      - name: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ format('v_{0}', steps.release_version.outputs.RELEASE_VERSION) }}
          tag: ${{ format('v_{0}', steps.release_version.outputs.RELEASE_VERSION) }}
          artifacts: 'release/*'
